# Generated by Django 4.1.3 on 2023-07-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_remove_zoomclassschedule_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomclass',
            name='repeat',
            field=models.BooleanField(default=True),
        ),
    ]
